### PR TITLE
add example images for edit and update in UG

### PR DESCRIPTION
**Pull request by dvdweien**

### CODE REVIEW

**Comment by dvdweien** [comment]
the images:

ExampleEditAppointment
ExampleEditProperty
ExampleUpdateNew

**Comment by candyhy** [comment]
> the images:
> 
> ExampleEditAppointment
> ExampleEditProperty
> ExampleUpdateNew

hmm I find your images to be rather cluttered in my opinion. @w2vgd what do u think?

**Comment by w2vgd** [comment]
> hmm I find your images to be rather cluttered in my opinion. @w2vgd what do u think?

Yeahh I agree. @dvdweien is it possible to reduce the thickness of borders of the boxes?

**Comment by dvdweien** [comment]
i tried, is this better?

ExampleEditAppointment
ExampleEditProperty
ExampleUpdateNew

**Review by candyhy — APPROVED** [review]
Much better now, thanks

**Pull request merged**
