### PR TITLE
Add diagrams to help explain Update in DG

### PR DESCRIPTION
**Pull request by dvdweien**

### CODE REVIEW

**Comment by candyhy** [comment]
ohya can u upload your diagrams here for everyone to see?

**Comment by dvdweien** [comment]
StatusClassDiagram
UpdateCommandClassDiagram
UpdateStep1Initial
UpdateStep2New
UpdateStep3Proceed
UpdateStep4Proceed
UpdateStep5Cancel
UpdateActivityDiagram
UpdateNewSequenceDiagram

**Comment by w2vgd** [comment]
1. This shouldn't be execute(undo) right
2. I think should enclose the parameter in quotes cuz its supposed to be a string
3. should be dotted line for returning
4. This is a constructor call, so the label shouldn't be 600000 I think. Either leave it blank or change it to a call to create a new Option object
5. should be dotted line for returning
6. should be dotted line for returning
7. missing returning dotted line (if everywhere else has a returning dotted line, then u should  probably include one here too)

image

**Comment by w2vgd** [comment]
Your diagram:
image

My diagram:
image

For this, I do agree that the 3 child classes should have a composition relationship with `Offer`, and I will update my diagram. But do you think there should be a dependency arrow from `Status` to `Offer` as well?

**Comment by dvdweien** [comment]
> 1. This shouldn't be execute(undo) right
> 2. I think should enclose the parameter in quotes cuz its supposed to be a string
> 3. should be dotted line for returning
> 4. This is a constructor call, so the label shouldn't be 600000 I think. Either leave it blank or change it to a call to create a new Option object
> 5. should be dotted line for returning
> 6. should be dotted line for returning
> 7. missing returning dotted line (if everywhere else has a returning dotted line, then u should  probably include one here too)
> 
> image

Thanks! I will fix 1-6 but for 7 i was thinking that cos its a void method and doesn't return anything so I omitted it

**Comment by dvdweien** [comment]
> Your diagram:
> image
> 
> My diagram:
> image
> 
> For this, I do agree that the 3 child classes should have a composition relationship with `Offer`, and I will update my diagram. But do you think there should be a dependency arrow from `Status` to `Offer` as well?

I don't think there should be a dependency arrow from Status to Offer as Status doesn't actually have any knowledge of Offer, Offer is only referenced in the classes that implement Status

**Comment by dvdweien** [comment]
the updated sequence diagram

UpdateNewSequenceDiagram

**Comment by w2vgd** [comment]
> I don't think there should be a dependency arrow from Status to Offer as Status doesn't actually have any knowledge of Offer, Offer is only referenced in the classes that implement Status

Ohh, because I thought `Status` has a method returning an `Offer` object. Hmm, not really sure whether to include this dependency arrow...
image

**Comment by dvdweien** [comment]
> > I don't think there should be a dependency arrow from Status to Offer as Status doesn't actually have any knowledge of Offer, Offer is only referenced in the classes that implement Status
> 
> Ohh, because I thought `Status` has a method returning an `Offer` object. Hmm, not really sure whether to include this dependency arrow...
> image

Oh yeah! I forgot about that, that method isn't currently being used now should i remove it? If it shouldn't be removed then i will add the dependency arrow

**Comment by w2vgd** [comment]
> > > I don't think there should be a dependency arrow from Status to Offer as Status doesn't actually have any knowledge of Offer, Offer is only referenced in the classes that implement Status
> > 
> > 
> > Ohh, because I thought `Status` has a method returning an `Offer` object. Hmm, not really sure whether to include this dependency arrow...
> > image
> 
> Oh yeah! I forgot about that, that method isn't currently being used now should i remove it? If it shouldn't be removed then i will add the dependency arrow

Ohh, its not being used? Then ya please remove and I will update my diagram. Thanks!

**Comment by dvdweien** [comment]
> > > > I don't think there should be a dependency arrow from Status to Offer as Status doesn't actually have any knowledge of Offer, Offer is only referenced in the classes that implement Status
> > > 
> > > 
> > > Ohh, because I thought `Status` has a method returning an `Offer` object. Hmm, not really sure whether to include this dependency arrow...
> > > image
> > 
> > 
> > Oh yeah! I forgot about that, that method isn't currently being used now should i remove it? If it shouldn't be removed then i will add the dependency arrow
> 
> Ohh, its not being used? Then ya please remove and I will update my diagram. Thanks!

I just removed it!

**Review by w2vgd — APPROVED** [review]
LGTM

**Pull request merged**
