### PR TITLE
Make light theme consistent

### PR DESCRIPTION
**Pull request by dvdweien**
current state:
image

not the best at styling as you can see...
Extremely open to suggestions! Is this blue ok? or should we just go with white? or a shade or grey?
was unable to make the resultdisplay rounded

### CODE REVIEW

**Comment by w2vgd** [comment]
@candyhy what do you think of this 🤔

**Comment by candyhy** [comment]
> @candyhy what do you think of this 🤔

I think it is too colourful, better to keep it minimalist. That purple doesn't go with the blue either

**Comment by candyhy** [comment]
can I also suggest keeping the text wrapping fixes and changes to Ui as separate pull requests? cos I think its imperative to fix the text wrapping but the Ui may not be satisfactory yet

**Comment by dvdweien** [comment]
> > @candyhy what do you think of this thinking
> 
> I think it is too colourful, better to keep it minimalist. That purple doesn't go with the blue either

what colour would you suggest?

**Comment by dvdweien** [comment]
> can I also suggest keeping the text wrapping fixes and changes to Ui as separate pull requests? cos I think its imperative to fix the text wrapping but the Ui may not be satisfactory yet

created a separate pr for text wrap!

**Comment by candyhy** [comment]
> > can I also suggest keeping the text wrapping fixes and changes to Ui as separate pull requests? cos I think its imperative to fix the text wrapping but the Ui may not be satisfactory yet
> 
> created a separate pr for text wrap!

cool thanks! 👍

**Comment by candyhy** [comment]
> > > @candyhy what do you think of this thinking
> > 
> > 
> > I think it is too colourful, better to keep it minimalist. That purple doesn't go with the blue either
> 
> what colour would you suggest?

I think its better to keep the background white/black. shouldn't have more than 3 colours in a Ui in my opinion

**Comment by dvdweien** [comment]
> > > > @candyhy what do you think of this thinking
> > > 
> > > 
> > > I think it is too colourful, better to keep it minimalist. That purple doesn't go with the blue either
> > 
> > 
> > what colour would you suggest?
> 
> I think its better to keep the background white/black. shouldn't have more than 3 colours in a Ui in my opinion

like this?

image

or this?

image

**Pull request closed without merging**
